import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>
        <title>Manutention Beaujolaise</title>
        <link rel="icon" href="/Icon.png" />
      </head>
      <html lang="en">
        <body className={`${inter.className}overflow-scroll scrolllg `}>{children}</body>
      </html>
    </>

  );
}
